# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: atlas-cli-plugin-example

version: 2

builds:
  - 
    id: "atlas-cli-plugin-example"
    main: ./cmd/plugin/main.go
    binary: ./binary

archives:
  - files:
      - src: "./manifest{{ if eq .Os \"windows\" }}.windows{{end}}.yml"
        dst: ./manifest.yml
