# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: atlas-cli-first-class-plugin-example

version: 2

builds:
  - 
    id: "atlas-cli-first-class-plugin-example"
    main: ./cmd/plugin/main.go
    binary: ./binary

archives:
  - files:
      - src: "./manifest.yml"
        dst: ./manifest.yml
